name: basalt
description: An immutable Linux distribution for the PinePhone based on Fedora Silverblue.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copies config/files/usr into your image's /usr.
                  # put configuration files you want in /etc/ on a booted system 
                  # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/njha/mobile/repo/fedora-40/njha-mobile-fedora-40.repo
    install:
      - megi-kernel
      - feedbackd
      - phoc
      - phosh
      - squeekboard
      - ModemManager
      - rtl8723cs-firmware
      - chatty
      - calls
      - carbons
      - purple-mm-sms
      - pinephone-helpers
      - epiphany
      - NetworkManager-wwan
      - gvfs-goa
      - megapixels
      - gnome-power-manager
      - gnome-usage
      - xdg-user-dirs
      - pipewire-alsa
      - pipewire-pulseaudio
      - alsa-ucm
      - pp-uboot
      - wlr-randr
      - gnome-clocks
      - wireplumber
    remove:
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      # repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      # repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - io.gitlab.librewolf-community
      remove:
      # - org.gnome.eog

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

